sweeputil.pacesweep('liu_rwglasso_roc', ...
  '+experiments/+static/+liu_rwglasso_roc/run.m', ...
  'excludedirs',   {'+algs', '+datasets', '+experiments', '+visualize',}, ...
  'queue',         'rozell', ...
  'walltime',      '48:00:00', ...
  'matlabversion', 'r2016b', ...
  'username',      'moshaughnessy6', ...
  'headnode',      'login-d', ...
  'email',         'moshaughnessy6@gatech.edu', ...
  'mem',           '100gb', ...
  'nodes',         1, ...
  'ppn',           28);