% Create ROC curves to test LSM-derived reweighted graphical model for
% incorporating dynamics based estimates

params = struct( ...
  'pinnov',   [0 0.15 0.3 1.0], ...
  'lambda0',  logspace(-2,1,10), ...
	'xi',       logspace(-3,1,10), ...
  'eta',      logspace(-2,0,5), ...
	'randseed', 1:14);

varsToStore = {'err'};

scriptname = 'experiments.static.rwglasso_roc.script';
if strfind(getenv('HOSTNAME'),'.pace.gatech.edu')
  resultsJOBNUM = sweep(scriptname, params, ...
    'varsToStore', varsToStore, ...
    'jobNum', JOBNUM, 'totalJobs', TOTALJOBS);
  save('resultsJOBNUM','resultsJOBNUM');
else
  results = sweep(scriptname, params, ...
    'varsToStore', varsToStore);
  save('+experiments/+static/+rwglasso_roc/results','results');
end

